Lapka.Pet.Api without Advertisement and likes
MlabCommunity/LapkaBackend pull request #15
Opened 2023-08-08 12:12 UTC by SlawomirJJ

2023-08-09 10:20 UTC, pswierad-src requested changes
Dodaj async metody tam gdzie to możliwe
Trzymajmy się konwencji  nazywania var zmienna = new Obiekt();
Staraj się tak konstruować ify żeby ewentualne wyjątki rzucać od razu - unikniesz wtedy piętrowych ifów dzięki czemu kod będzie czytelniejszy
Przepatrz parametry i pola metod i usuń te nie używane
Ujednolić całą walidację - jak jest fluent validation to używajmy tego do walidacji wszystkiego - chodzi mi głównie o [Required] tam gdzie mógłby być validator
Konfigurację encji robimy tylko przez fluent api

2023-08-09 10:20 UTC, pswierad-src commented on LapkaBackend.Application/Functions/Command/HidePetCommand.cs
> +            var pet = _dbContext.Animals.FirstOrDefault(x => x.Id == petId);
metoda jest asynchroniczna to użyj FirstOrDefaultAsync ;)

2023-08-09 10:20 UTC, pswierad-src commented on LapkaBackend.Application/Functions/Command/UpdateShelterVolunteeringCommand.cs
> +                else
Tutaj ten else jest chyba nie potrzebny

2023-08-09 10:20 UTC, pswierad-src commented on LapkaBackend.Application/Functions/Command/UpdateShelterVolunteeringCommand.cs
Sprecyzuj co ma ta komenda robić? Dodawanie czy update - bo w tej chwili chyba robi obie te rzeczy - można by to jakoś rozbić?

2023-08-09 10:20 UTC, pswierad-src commented on LapkaBackend.Application/Functions/Queries/GetListOfSheltersQuery.cs
> +    public record GetListOfSheltersQuery : IRequest<List<ShelterInListDto>>;
Jakieś parametry tu na pewno można już założyć

2023-08-09 10:20 UTC, pswierad-src commented on LapkaBackend.Application/Functions/Queries/GetPetQuery.cs
> +    public record GetPetQuery(string Id) : IRequest<PetDto>;
Id jest stringiem czy guidem? Jak guidem to daj guid - wtedy od razu będzie próbowało mapować przy requeście i nie trzeba będzie sprawdzać czy jakichś głupot tam nie ma

2023-08-09 10:20 UTC, pswierad-src commented on LapkaBackend.Application/Functions/Queries/GetPetQuery.cs
> +                //User=
do usunięcia

2023-08-09 10:20 UTC, pswierad-src commented on LapkaBackend.Application/Functions/Queries/GetShelterByPositionQuery.cs
> +            List<Shelter> allShelters = await _dbContext.Shelters.ToListAsync();// lista wszystkich shronisk
Pomyśl czy nie można by zrobić tego filtrowania jakoś na IQueryable. Jakbyś miał 1000000 wpisów to zaciąganie wszystkich do pamięci i potem działanie na nich chwilę potrwa. 
W naszej sytuacji raczej nie będzie tego problemu ale nie ma co się złych praktyk uczyć

2023-08-09 10:20 UTC, pswierad-src commented on LapkaBackend.Application/Functions/Queries/GetShelterByPositionQuery.cs
> +    public class Response
Nie nazywaj tak generycznie klas. Potem będziesz miał 10 klas Response i nie dojdziesz która to która :P

2023-08-09 10:20 UTC, pswierad-src commented on LapkaBackend.Application/Functions/Queries/GetShelterQuery.cs
> +    public record GetShelterQuery : IRequest<ShelterDto>
To samo co wcześniej - nie rób z recordu klasy

2023-08-09 10:20 UTC, pswierad-src commented on LapkaBackend.Application/Functions/Queries/ShelterPetsViewsGroupByDaysInWeekQuery.cs
> +            var result = new List<int>(numberOfDays);
Nie musisz definiować capacity przy liście - nawet się raczej nie powinno

2023-08-09 10:20 UTC, pswierad-src commented on LapkaBackend.Domain/Entities/Animal.cs
> +        public virtual List<Photo>? Photos { get; set; }
? nie potrzebny. Pola virtualne z reguły są lazy loadowane

Dotyczy każdego virtuala użytego do relacji.

2023-08-09 10:20 UTC, pswierad-src commented on LapkaBackend.Domain/Entities/AnimalView.cs
> +        [ForeignKey("AnimalId")]
te klucze obce powinny być skonfigurowane prze fluent api.

2023-08-09 10:20 UTC, pswierad-src commented on LapkaBackend.Domain/Enums/AnimalCategories.cs
> +        Undefined,
Zawsze numeruj enumy - przyjdzie ci kiedyś jakiś śmieszek i doda wartość pomiędzy cat i dog i ci się cała numeracja rozjedzie

2023-08-09 10:20 UTC, pswierad-src commented on LapkaBackend.Domain/Enums/Breeds.cs
> +    public enum Breeds
Tutaj przegadamy jeszcze czy rasy faktycznie jako enum robić, czy może jednak nie lepiej by było to jakoś inaczej trzymać.

Tak czy siak - enum do ponumerowania

2023-08-09 10:20 UTC, pswierad-src commented on LapkaBackend.Domain/Enums/Reactions.cs
> +        Like
Nieużywane - można usunąć

2023-08-10 11:59 UTC, SlawomirJJ commented on LapkaBackend.Application/Functions/Command/CreatePetCardCommand.cs
> +                    if (request.Breed.ToString().StartsWith("Cat") || request.Breed.ToString() == "Inna")
Chodzi o to że w enumie są nazwy ras dla wszystkich zwierząt. Ten fragment sprawdza czy ktoś nie przypisał rasy która jest przypisana do innego gatunku zwierząt niż ten który wybrał. Nazwy ras zaczynają się od nazwy gatunku zwierzęcia dlatego użyłem starts with. Na froncie zrobili też walidację ale Karol mi powiedział że na backendzie też mogę zrobić.

2023-08-16 11:41 UTC, pswierad-src commented on LapkaBackend.API/Controllers/ShelterController.cs
> +            var query = new GetListOfSheltersQuery();
Można to w jednej linijce zrobić :)

2023-08-16 11:42 UTC, pswierad-src commented on LapkaBackend.API/Controllers/ShelterController.cs
> +            var query = new GetShelterQuery(shelterId);
Query czy commandy można przyjmować w jako parametry w endpoincie. Tutaj to różnicy nie zrobi ale jak masz dużo parametrów to obiekt ładniej wygląda

2023-08-16 11:44 UTC, pswierad-src commented on LapkaBackend.Application/Functions/Command/UpdatePetCommand.cs
> +                if (i==0)
Czy zawsze przy update zakładamy że pierwsze zdjęcie jest profilowym?

2023-08-18 08:40 UTC, merged